app:
    build: ./app
    volumes:
        - /local/project/dir:/var/www/APP_NAME
        - logs/APP_NAME:/var/www/APP_NAME/var/logs
    tty: true
db_APP_NAME:
    image: mysql:latest
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: ROOT_PWD
        MYSQL_DATABASE: DB_NAME
        MYSQL_USER: DB_USER
        MYSQL_PASSWORD: DB_PWD
dev:
    build: ./dev
    volumes_from:
        - app
php:
    build: ./php-fpm
    expose:
        - 9000:9000
    volumes_from:
        - app
    links:
        - db_APP_NAME
nginx:
    build: ./nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app
    volumes:
        - logs/nginx/:/var/log/nginx
# elk:
#    image: willdurand/elk
#    ports:
#        - 81:80
#    volumes:
#        - elk/logstash:/etc/logstash
#        - elk/logstash/patterns:/opt/logstash/patterns
#    volumes_from:
#        - app
#        - php
#        - nginx