app:
    build: ./app
    volumes:
        - /your/local/projects/dir:/usr/share/nginx/html
    tty: true
db:
    image: mysql:latest
    ports:
        - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: docker_app
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
# dev:
#     build: ./dev
#     volumes_from:
        # - app
php:
    build: ./php-fpm
    expose:
        - 9000:9000
    links:
        - db
    volumes_from:
        - app
    volumes:
        - logs/php/:/var/log/php
nginx:
    build: ./nginx
    ports:
        - 80:80
    links:
        - php
    volumes_from:
        - app
    volumes:
        - logs/nginx/:/var/log/nginx
# elk:
#    image: willdurand/elk
#    ports:
#        - 81:80
#    volumes:
#        - elk/logstash:/etc/logstash
#        - elk/logstash/patterns:/opt/logstash/patterns
#    volumes_from:
#        - app
#        - php
#        - nginx